### ISSUE TITLE
Unable to Cargo Workspace

### ISSUE THREAD

**Issue by ca-mantis-shrimp** [williamboman/nvim-lsp-installer#375] opened 2022-01-01 03:17 UTC
**Describe the bug**
So I've been using LSP-Installer for awhile now, and what is really weird is that my config was working a few days ago!

I'm trying to make this work with the rust-tools extension, but this bug shows up whether I configure it with the rust-tools plugin, or simply using the basic rust-analyzer setup laid out in the README. I have a pretty minimal configuration, and besides a basic configuration for sumneko lua, rust is the only language I am trying to get working at the moment (so no complex LSP switching logic).

The reason I think this is an lis-installer issue is because I can get the configuration working fine if I create the LSP server using only the rust-tools plugin.
- i'm also able to get it working with normal lspconfig.

So this is why I think it is an lsp-install issue that may have arisen from a recent change in the rust analyzer code.

**Expected behavior**
When I open a rust file, I expect to simply begin editing, and see diagnostics as I begin typing.

- specifically, I seem to lose diagnostics while I type, and while some LSP completions still work, It doesn't seem to have access to variables within the workspace.

**Screenshots**
![image](https://user-images.githubusercontent.com/25948785/147843090-25b88cb5-73f5-46cd-9414-811f3abc45f2.png)
- workpace error on new cargo project
![image](https://user-images.githubusercontent.com/25948785/147843094-0234e561-7a3e-4962-bb4b-bb7199709b0c.png)
- minimal LSP config
![image](https://user-images.githubusercontent.com/25948785/147843110-46710dad-2968-48b7-a588-a09caefa62dd.png)
- clear case of a broken code segment without any LSP diagnostics
![image](https://user-images.githubusercontent.com/25948785/147843119-5bdf429c-651e-4b92-b563-a63cd0c12009.png)
- LSP info
![image](https://user-images.githubusercontent.com/25948785/147843230-a8fa6878-bd85-4b02-8407-3126316147b9.png)
- LspInstallInfo for Rust Analyzer (seems fine?)
- I've installed, updated, and re-install rust analyzer multiple times now. It seems to install fine each time, I just can't access the workspace from it.

**System info (please complete the following information):**
Windows 10
- WSL 2
- Debian for the OS
- Neovim .6 AppImage
Checkhealth output (`:checkhealth nvim-lsp-installer`):

```

  1 nvim-lsp-installer: require("nvim-lsp-installer.health").check()
  2 ========================================================================
  3 ## nvim-lsp-installer report
  4 │ - WARNING: **Go**: not available
  5 │ - WARNING: **Ruby**: not available
  6 │ - WARNING: **RubyGem**: not available
  7 │ - WARNING: **Composer**: not available
  8 │ - WARNING: **PHP**: not available
  9 │ - WARNING: **javac**: not available
 10 │ - WARNING: **java**: not available
 11 │ - OK: **sh**: `Ok`
 12 │ - OK: **bash**: `GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)`
 13 │ - OK: **tar**: `tar (GNU tar) 1.34`
 14 │ - OK: **gzip**: `gzip 1.10`
 15 │ - OK: **wget**: `GNU Wget 1.21 built on linux-gnu.`
 16 │ - OK: **python3**: `Python 3.9.2`
 17 │ - OK: **curl**: `curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0         librtmp/2.3`
 18 │ - WARNING: **pip3**: not available
 19 │ - WARNING: **node**: unsupported version `v12.22.5`. Node version must be >= 14
 20 │ - OK: **npm**: `7.5.2`
```

Please also include any other system information you think is relevant!

**Install log**
Not applicable, rust analyzer seems to be installed fine, but the plugin is having trouble seeing the actual workspace

Thank you for taking the time to read my Issue, happy to answer any questions. Appreciate the work, love using your plugin!

**Comment by williamboman** [comment] 2022-01-02 12:22
Hello! When you're able to set it up via both rust-tools and lspconfig, are all other things equal (i.e., exact same project, same system, same version of `rust-analyzer`)? After some quick research, `os error 5` seems to be some WSL-related file permission error.

What does the LSP log say? `:exe 'tabnew ' .. luaeval("vim.lsp.get_log_path()")`

**Comment by ca-mantis-shrimp** [comment] 2022-01-02 23:25
Hey @williamboman, 

TY for your time! I will answer in order.
1. Yes, in order to minimize variable I reduced both functions down to their base state. Specifically, I just ran an empty setup for the rust tools, and as close to an empty setup for LspConfig as well. Both are using an instance of rust-analyzer that I installed by building from source with the `--server` flag.
2. Here is the output I receive: ```[ERROR][2022-01-02 17:18:35] .../vim/lsp/rpc.lua:417    "rpc"   "rust-analyzer" "stderr"        '[ERROR rust_analyzer::reload] failed to switch workspaces: rust-analyzer failed to load     workspace: "cargo" "--version" failed: Input/output error (os error 5)\n\n'```

**Comment by ca-mantis-shrimp** [comment] 2022-01-03 00:24
Posting a follow-up. 

So today I updated to 0.6.1 AppImage. 

I now get the error that runs when you try to open a rust file while rust-tools is installed, but didn't actually run the `setup` function
```
Error Code: Error detected while processing VimEnter Autocommands for "*.rs":
E5108: Error executing lua ...ite/pack/packer/start/rust-tools.nvim/lua/rust-tools.lua:176: attempt to index local 'lsp_opts' (a nil value)
stack traceback:
        ...ite/pack/packer/start/rust-tools.nvim/lua/rust-tools.lua:176: in function 'start_standalone_if_required'
        [string ":lua"]:1: in main chunk
```

This implies that the new startup changes that recently came to rust-tools as part of the standalone support might break how we actually do this.

**Comment by williamboman** [comment] 2022-01-11 13:07
> I now get the error that runs when you try to open a rust file while rust-tools is installed, but didn't actually run the `setup` function

Ah so you can now reproduce the issue without using nvim-lsp-installer? I'm at a loss as to what might be happening - if I had to guess this is a WSL-specific file permissions issue. If there was a reproducible minimal config or environment, this would be easier to debug from my end.

**Comment by ca-mantis-shrimp** [comment] 2022-01-16 18:52
> > I now get the error that runs when you try to open a rust file while rust-tools is installed, but didn't actually run the `setup` function
> 
> Ah so you can now reproduce the issue without using nvim-lsp-installer? I'm at a loss as to what might be happening - if I had to guess this is a WSL-specific file permissions issue. If there was a reproducible minimal config or environment, this would be easier to debug from my end.

Ill rework my config in a new branch to get a minimal config. Thank you for your patience and help!

**Comment by williamboman** [comment] 2022-02-16 20:54
Hey so I've created a new issue template for these kinds of issues, it contains a `minimal_debug_init.lua` which should be used when describing how to reproduce the issue. I'll close this issue as I'm unable to reproduce it, but please file a new one using the issue template if you think it's still relevant!

<img width="1281" alt="Screenshot 2022-02-16 at 21 33 46" src="https://user-images.githubusercontent.com/6705160/154355089-0134a3e0-5cf9-4c77-b54f-be3e50ada3ef.png">

**Closed by williamboman** 2022-02-16 20:54 UTC
Labels: bug

**Comment by ca-mantis-shrimp** [comment] 2022-03-27 17:04
Just a final comment before I leave this. I should note that this workspace error went away with one of the recent updates to rust-tools, I think there was just a temporary workspace bug that should be fixed now with the newest version of rust tools. Thanks as always for your triage and patience!
